# syntax=docker/dockerfile:1

FROM node:20 AS base

RUN npm install --global pnpm

RUN sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list.d/debian.sources

# Install dependencies
RUN apt-get update && apt-get install -y python3 ffmpeg make g++ build-essential && rm -rf /var/lib/apt/lists/*

# Stage 1: install dependencies with workspace context
FROM base AS builder

WORKDIR /repo

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY scripts ./scripts
COPY patches ./patches

COPY packages/ packages/

RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
  pnpm --filter happy-app deploy /app/

# Stage 3: runtime
FROM base AS runner

WORKDIR /app

# Set environment to production
ENV NODE_ENV=production

# Copy necessary files from the builder stage
COPY --from=builder /app /app

ENV DATA_DIR=/data
ENV PGLITE_DIR=/data/pglite

VOLUME /data

EXPOSE 8081

# Command to run the application
ENTRYPOINT ["/bin/bash", "-c", "pnpm run web"]
